import React, { useState } from 'react';
import { motion } from 'framer-motion';
import LegalModal from './LegalModal';

const Footer: React.FC = () => {
  const [modalType, setModalType] = useState<'privacy' | 'terms' | null>(null);

  const renderModalContent = () => {
    if (modalType === 'privacy') {
      return (
        <>
          <p style={{ marginBottom: '1.5rem' }}><strong>Effective Date:</strong> {new Date().toLocaleDateString()}</p>
          <p style={{ marginBottom: '1.5rem' }}>Welcome to Gerald Balete's portfolio website. This Privacy Policy explains how your information is collected, used, and protected when you interact with this website.</p>
          
          <h3 style={{ marginTop: '1.5rem', marginBottom: '0.75rem', color: 'var(--text-main)', fontSize: '1.1rem' }}>1. Information We Collect</h3>
          <p style={{ marginBottom: '1rem' }}>We may collect personal information that you voluntarily provide when you use our contact form or interact with our AI Chat Assistant. This may include your name, email address, and the contents of your messages.</p>
          
          <h3 style={{ marginTop: '1.5rem', marginBottom: '0.75rem', color: 'var(--text-main)', fontSize: '1.1rem' }}>2. How We Use Your Information</h3>
          <p style={{ marginBottom: '0.5rem' }}>The information collected is strictly used for the following purposes:</p>
          <ul style={{ paddingLeft: '1.5rem', marginBottom: '1.5rem', listStyleType: 'disc' }}>
            <li style={{ marginBottom: '0.25rem' }}>To respond to your inquiries and messages.</li>
            <li style={{ marginBottom: '0.25rem' }}>To improve the functionality and user experience of the portfolio.</li>
            <li style={{ marginBottom: '0.25rem' }}>To monitor and prevent abuse of the contact form and AI Chat features.</li>
          </ul>

          <h3 style={{ marginTop: '1.5rem', marginBottom: '0.75rem', color: 'var(--text-main)', fontSize: '1.1rem' }}>3. AI Chat Assistant</h3>
          <p style={{ marginBottom: '1rem' }}>Interactions with the AI Chat Assistant may be processed to generate responses. Please avoid sharing highly sensitive or confidential information in the chat.</p>

          <h3 style={{ marginTop: '1.5rem', marginBottom: '0.75rem', color: 'var(--text-main)', fontSize: '1.1rem' }}>4. Third-Party Services</h3>
          <p style={{ marginBottom: '1rem' }}>We do not sell, trade, or otherwise transfer your personal information to outside parties. However, we may use trusted third-party services (like EmailJS or AI providers) to facilitate website operations, subject to their respective privacy policies.</p>

          <h3 style={{ marginTop: '1.5rem', marginBottom: '0.75rem', color: 'var(--text-main)', fontSize: '1.1rem' }}>5. Contact Us</h3>
          <p style={{ marginBottom: '1rem' }}>If you have any questions about this Privacy Policy, please contact us via the contact form on this website.</p>
        </>
      );
    }
    if (modalType === 'terms') {
      return (
        <>
          <p style={{ marginBottom: '1.5rem' }}><strong>Effective Date:</strong> {new Date().toLocaleDateString()}</p>
          <p style={{ marginBottom: '1.5rem' }}>By accessing and using this portfolio website, you accept and agree to be bound by the terms and provisions of this agreement.</p>
          
          <h3 style={{ marginTop: '1.5rem', marginBottom: '0.75rem', color: 'var(--text-main)', fontSize: '1.1rem' }}>1. Intellectual Property</h3>
          <p style={{ marginBottom: '1rem' }}>All content on this website, including text, graphics, logos, images, and software code, is the property of Gerald Balete unless otherwise noted. You may not reproduce, distribute, or create derivative works without prior written consent.</p>
          
          <h3 style={{ marginTop: '1.5rem', marginBottom: '0.75rem', color: 'var(--text-main)', fontSize: '1.1rem' }}>2. User Conduct</h3>
          <p style={{ marginBottom: '0.5rem' }}>When using features such as the contact form or AI Chat Assistant, you agree not to:</p>
          <ul style={{ paddingLeft: '1.5rem', marginBottom: '1.5rem', listStyleType: 'disc' }}>
            <li style={{ marginBottom: '0.25rem' }}>Submit spam, harmful, or abusive content.</li>
            <li style={{ marginBottom: '0.25rem' }}>Attempt to compromise the security or functionality of the website.</li>
            <li style={{ marginBottom: '0.25rem' }}>Use automated scripts or bots to extract information or interact with the site.</li>
          </ul>

          <h3 style={{ marginTop: '1.5rem', marginBottom: '0.75rem', color: 'var(--text-main)', fontSize: '1.1rem' }}>3. AI Chat Limitations</h3>
          <p style={{ marginBottom: '1rem' }}>The AI Chat Assistant is provided for informational and demonstrative purposes only. Responses generated by the AI may not always be completely accurate. We reserve the right to restrict or terminate chat access for any abusive behavior.</p>

          <h3 style={{ marginTop: '1.5rem', marginBottom: '0.75rem', color: 'var(--text-main)', fontSize: '1.1rem' }}>4. Disclaimer of Warranties</h3>
          <p style={{ marginBottom: '1rem' }}>This website is provided on an "as is" and "as available" basis. We make no warranties, expressed or implied, regarding the operation or availability of the website.</p>

          <h3 style={{ marginTop: '1.5rem', marginBottom: '0.75rem', color: 'var(--text-main)', fontSize: '1.1rem' }}>5. Changes to Terms</h3>
          <p style={{ marginBottom: '1rem' }}>We reserve the right to modify these terms at any time. Your continued use of the website following any changes constitutes acceptance of those changes.</p>
        </>
      );
    }
    return null;
  };

  return (
    <>
      <footer style={{ position: 'relative', background: '#0a0a0a', borderTop: 'none', color: 'rgba(255, 255, 255, 0.6)' }}>
        {/* Animated Wave Divider */}
        <div style={{ position: 'absolute', top: '-100px', left: 0, width: '100%', overflow: 'hidden', lineHeight: 0, zIndex: 10 }}>
          <motion.svg
            animate={{ x: ['0%', '-50%'] }}
            transition={{ repeat: Infinity, duration: 25, ease: 'linear' }}
            viewBox="0 0 2000 100"
            preserveAspectRatio="none"
            style={{ display: 'block', width: '200%', height: '101px' }}
          >
            <path d="M 0 50 Q 250 0, 500 50 T 1000 50 T 1500 50 T 2000 50 L 2000 100 L 0 100 Z" fill="#0a0a0a" />
            <path d="M 0 50 Q 250 100, 500 50 T 1000 50 T 1500 50 T 2000 50 L 2000 100 L 0 100 Z" fill="#0a0a0a" opacity="0.4" />
          </motion.svg>
        </div>
        
        <div className="container" style={{ position: 'relative', zIndex: 2, padding: '4rem 0', textAlign: 'center' }}>
          <p style={{ fontWeight: 500, color: 'rgba(255, 255, 255, 0.8)' }}>Copyright &copy; {new Date().getFullYear()} Gerald Balete. All rights reserved.</p>
          <div style={{ display: 'flex', justifyContent: 'center', gap: '1.5rem', marginTop: '1.5rem' }}>
            <button 
              onClick={() => setModalType('privacy')} 
              style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 0, color: 'rgba(255, 255, 255, 0.6)', textDecoration: 'none', transition: 'color 0.3s' }} 
              onMouseEnter={e => e.currentTarget.style.color = '#fff'} 
              onMouseLeave={e => e.currentTarget.style.color = 'rgba(255, 255, 255, 0.6)'}
            >
              Privacy Policy
            </button>
            <span style={{ color: 'rgba(255, 255, 255, 0.3)' }}>|</span>
            <button 
              onClick={() => setModalType('terms')} 
              style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 0, color: 'rgba(255, 255, 255, 0.6)', textDecoration: 'none', transition: 'color 0.3s' }} 
              onMouseEnter={e => e.currentTarget.style.color = '#fff'} 
              onMouseLeave={e => e.currentTarget.style.color = 'rgba(255, 255, 255, 0.6)'}
            >
              Terms of Use
            </button>
          </div>
        </div>
      </footer>

      <LegalModal 
        isOpen={modalType !== null} 
        onClose={() => setModalType(null)} 
        title={modalType === 'privacy' ? 'Privacy Policy' : 'Terms of Use'}
      >
        {renderModalContent()}
      </LegalModal>
    </>
  );
};

export default Footer;
